/**
 * Author : Ahmed Atef Eid Eid 
 * Date   : 30-9-2024
 * Title  : Number Guessing Game Guessing_Game.h File
 */

#ifndef GUESSING_GAME_H
#define GUESSING_GAME_H



/**
 * @brief Prints the welcome message for the game.
 * 
 * This function displays a message introducing the player to the 
 * guessing game and providing the range of the target number.
 */
void PrintWelcomeMessage(void);

/**
 * @brief Prompts the user to enter a valid guess between 1 and 100.
 * 
 * This function will continue to prompt the user until a valid number 
 * is entered. It checks for invalid input and ensures the guess is 
 * within the range.
 * 
 * @return unsigned char The valid number entered by the user.
 */
unsigned char GetNumberFromUser(void);

/**
 * @brief Generates a random number between 1 and 100.
 * 
 * This function uses a time-based seed to ensure that a unique 
 * random number is generated each time the game is played.
 * 
 * @return unsigned char The randomly generated number.
 */
unsigned char GenerateRandomNumber(void);

/**
 * @brief Prints feedback based on the user's guess.
 * 
 * This function compares the guessed number to the randomly generated 
 * number and provides feedback to guide the player.
 * 
 * @param[in] EnteredNum The number entered by the user.
 * @param[in] RandomNum The random number generated by the game.
 */
void PrintStatusMessage(unsigned char EnteredNum, unsigned char RandomNum);

/**
 * @brief Runs the guessing game algorithm.
 * 
 * This function continuously prompts the user for guesses until the 
 * correct number is guessed. It generates a random number at the 
 * beginning and provides feedback after each guess.
 */
void RunAlgorithm(void);


#endif